<?php

/**
 * Implemetation of hook_menu().  
 */
function flippingbook_menu() {
  $menu['admin/content/flippingbook-settings'] = array(
    'title' => 'FlippingBook Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flippingbook_admin_settings_form'),
    'access arguments' => array('administer content types'),
    'file' => 'flippingbook.admin.inc',
  );

  $menu['node/%node/flippingbook'] = array(
    'page callback' => 'flippingbook_view',
    'page arguments' => array(1),
    'access callback' => 'flippingbook_access',
    'access arguments' => array('view', 1),
  );
  
  $menu['node/%node/flippingbook-settings'] = array(
    'title' => 'FlippingBook Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('flippingbook_edit_form', 1),
    'access callback' => 'flippingbook_access',
    'access arguments' => array('edit', 1),
    'file' => 'flippingbook.edit_form.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  $menu['flippingbook-contents-ahah'] = array(
    'description' => 'FlippingBook contents form AHAH callback',
    'page callback' => 'flippingbook_contents_ahah',
    'access callback' => true,
    'file' => 'flippingbook.edit_form.inc',
    'type' => MENU_CALLBACK,
  );

  return $menu;
}

/**
 * Implemetation of hook_theme().  
 */
function flippingbook_theme() {
  $theme['flippingbook'] = array(
    'arguments' => array(
      'flippingbook' => null,
      'current_page' => 1,
    ),
    'template' => 'flippingbook',
  );
  
  $theme['flippingbook_contents_form'] = array(
    'arguments' => array(
      'form' => null,
    ),
    'file' => 'flippingbook.edit_form.inc', 
  );

  return $theme;
}

/**
 * Implemetation of hook_perm(). 
 */
function flippingbook_perm() {
  return array('view flippingbook', 'edit flippingbook', 'edit flippingbook advanced settings');
}

/**
 * Implemetation of hook_nodeapi().
 */
function flippingbook_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'delete':
      db_query('DELETE FROM {flippingbook} WHERE nid = %d', $node->nid);
      break;
      
    case 'load': 
      $node_types = variable_get('flippingbook_node_types', array());
      if (@$node_types[$node->type]) { 
        return array('flippingbook' => (array)flippingbook_load($node));
      }
  }
}

/**
 * Implemetation of hook_link().
 */
function flippingbook_link($type, $object, $teaser = FALSE) {
  $links = array();

  if ($type == 'node' && flippingbook_access('view', $object)) {
    if (/*$teaser && */isset($object->flippingbook)) {
      $links['view_flippingbook'] = array(
        'title' => t('View FlippingBook'),
        'href' => "node/$object->nid/flippingbook",
      );
      
      $popup_url = url("node/$object->nid/flippingbook");
      $links['view_flippingbook_popup'] = array(
        'title' => t('View FlippingBook popup'),
        'href' => "node/$object->nid/flippingbook",
        'attributes' => array(
          'target' => '_blank',
          'onclick' => "window.open('$popup_url','','menubar=0,resizable=1'); return false;"
        ),
      );
    }
  }
  
  return $links;
}

/**
 * Check access to flippingbook pages
 * 
 * @param object $node
 * @param string $op
 * @return boolean
 */
function flippingbook_access($op = 'view', $node) {
  $node_types = variable_get('flippingbook_node_types', array());
  return @$node_types[$node->type] && user_access("$op flippingbook");
}

/**
 * Loads FlippingBook by node
 * 
 * @param object $node
 * @return FlippingBook|null
 */
function flippingbook_load($node) {
  list($src_field, $pages_field) = (array)_flippingbook_get_fields($node->type);
  if (!$src_field || !$pages_field) return;
    

  $pages = array();
  foreach ((array)$node->{$pages_field['field_name']} as $page) {
    $pages[] = '/'.$page['filepath'];
  }  
  $downloadURL = '/'. $node->{$src_field['field_name']}[0]['filepath'];
  
  $res  = db_query('SELECT * FROM {flippingbook} WHERE nid = %d', $node->nid);
  $book = db_fetch_object($res);
  
  $book->title = $node->title;
  $book->pages = $pages;
  $book->contents = unserialize($book->contents);
  $book->settings = unserialize($book->settings);
  $book->downloadURL = $downloadURL; 

  return (array)$book;
}

/**
 * Print FlippingBook
 * 
 * @param object $node
 */
function flippingbook_view($node, $current_page = 1) {
  print theme('flippingbook', $node->flippingbook, $current_page);
}

function _flippingbook_get_fields($node_type) {
  $fields = content_fields(null, $node_type);

  foreach ($fields as $field) {
    if ($field['type'] == 'filefield' && $field['widget']['module'] == 'pdf_to_imagefield') {
      return array($field, $fields[$field['widget']['target_imagefield']]);
    }
  }
}
